# Generated by Django 2.2.6 on 2019-10-31 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('stores', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300, verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='accounts.Partner', verbose_name='파트너')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='clients.Review', verbose_name='답글')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='stores.Store', verbose_name='가게')),
            ],
            options={
                'verbose_name': '파드너 피드백',
                'verbose_name_plural': '파트너 피드백',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new', models.BooleanField(default=False, verbose_name='신규등록')),
                ('is_approved', models.BooleanField(default=False, verbose_name='승인 여부')),
                ('company_name', models.CharField(max_length=100, verbose_name='상호')),
                ('business_registration_number', models.CharField(max_length=10, verbose_name='등록번호')),
                ('representative_name', models.CharField(max_length=30, verbose_name='대표자명')),
                ('business_address', models.CharField(max_length=100, verbose_name='업장소재지')),
                ('business_commencement_date', models.DateField(null=True, verbose_name='영업개시일')),
                ('business_type', models.CharField(max_length=30, null=True, verbose_name='업태')),
                ('business_item', models.CharField(max_length=30, null=True, verbose_name='종목')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Partner', verbose_name='파트너')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stores.Store', verbose_name='가게')),
            ],
            options={
                'verbose_name': '사업자등록증',
                'verbose_name_plural': '사업자등록증',
                'ordering': ['id'],
            },
        ),
    ]
